"""Synthetic response workbooks for Phase J, generated by copying the real
template and filling specific rows -- never hand-built from scratch, so
every variant inherits the template's real structure and scaffold.

Regenerate standalone with:

    python tests/make_synthetic.py

Files land in sample_data/ (git-ignored -- confidential-shaped fixtures
don't belong in version control; the generator does).
"""

from __future__ import annotations

import shutil
import sys
from datetime import date, timedelta
from pathlib import Path

import openpyxl

if __package__ in (None, ""):
    # Run directly (`python tests/make_synthetic.py`) rather than as a
    # module -- put the project root on sys.path so `app` resolves.
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.template_spec import COLUMNS, FIRST_DATA_ROW, LAST_DATA_ROW, SHEET_NAME

TEMPLATE_PATH = Path(__file__).resolve().parent.parent / "template" / "Format.xlsx"
OUTPUT_DIR = Path(__file__).resolve().parent.parent / "sample_data"

WINDOW_START = date(2021, 1, 1)
WINDOW_END = date(2026, 1, 14)

# Real rows in the template, for variants that need a specific known plaza.
ROW_SEHATGANJ = FIRST_DATA_ROW  # S.No 1
ROW_MAUHARI = FIRST_DATA_ROW + 1  # S.No 2
ROW_UJARA = FIRST_DATA_ROW + 2  # S.No 3


def _phone(row_num: int, slot: int) -> str:
    """A distinct, valid-shaped 10-digit number per (row, slot) -- distinct
    so rows never trip the duplicate-phone consistency check by accident."""
    return str(9_000_000_000 + row_num * 10 + slot)


# NAME validation rejects digits (correctly -- a person's name shouldn't
# contain "1"), so K/O need a cycled pool of real-looking names rather than
# "Name {slot}".
_MANAGER_NAMES = ["Rahul Sharma", "Amit Kumar", "Suresh Babu", "Vijay Singh", "Manoj Verma", "Ravi Chandran", "Ajay Patel", "Deepak Rao"]
_TEAM_LEAD_NAMES = ["Priya Devi", "Anita Rao", "Deepa Nair", "Sunita Joshi", "Kavita Reddy", "Meena Iyer", "Neha Gupta", "Pooja Menon"]


def _valid_agency_block(row_num: int, n: int) -> dict[str, str]:
    """{column letter: cell text} for H..R with N valid, chained,
    window-covering agencies -- the clean baseline every variant starts
    from before introducing its one deliberate break."""
    total_days = (WINDOW_END - WINDOW_START).days
    boundaries = [WINDOW_START + timedelta(days=round(total_days * i / n)) for i in range(n + 1)]

    cols: dict[str, list[str]] = {c: [] for c in "HIJKLMNOPQR"}
    for slot in range(1, n + 1):
        start, end = boundaries[slot - 1], boundaries[slot]
        cols["H"].append(f"{slot}. Agency {slot} Pvt Ltd")
        cols["I"].append(f"{slot}. {'EQ (3 months)' if slot % 2 else 'Regular (1 year)'}")
        cols["J"].append(f"{slot}. {start.strftime('%d/%m/%Y')} - {end.strftime('%d/%m/%Y')}")
        cols["K"].append(f"{slot}. {_MANAGER_NAMES[(slot - 1) % len(_MANAGER_NAMES)]}")
        cols["L"].append(f"{slot}. {_phone(row_num, slot)}")
        cols["M"].append(f"{slot}. Toll Plaza Road, Sample City {slot}")
        cols["N"].append(f"{slot}. Consultant Firm {slot}")
        cols["O"].append(f"{slot}. {_TEAM_LEAD_NAMES[(slot - 1) % len(_TEAM_LEAD_NAMES)]}")
        cols["P"].append(f"{slot}. HTMS Expert {slot}")
        cols["Q"].append(f"{slot}. {1000 + slot}")
        cols["R"].append(f"{slot}. {100 + slot}")

    return {letter: "\n".join(lines) for letter, lines in cols.items()}


def _fill_row(ws, row_num: int, n: int, **overrides: str) -> None:
    values: dict[str, str] = {
        "F": f"Sample Village {row_num}, Chainage 10+{row_num:03d}, Sample City, {460000 + row_num}",
        "G": "BOT",
        "S": "Filled by synthetic generator",
    }
    values.update(_valid_agency_block(row_num, n))
    values.update(overrides)
    for letter, text in values.items():
        ws.cell(row=row_num, column=COLUMNS[letter].index, value=text)


def _open_template() -> tuple[openpyxl.Workbook, "openpyxl.worksheet.worksheet.Worksheet"]:
    wb = openpyxl.load_workbook(TEMPLATE_PATH)
    return wb, wb[SHEET_NAME]


# ============================================================================
# The 12 variants
# ============================================================================


def make_untouched(dest: Path) -> None:
    """Expectation: 0% completeness, all 115 rows MISSING."""
    shutil.copy(TEMPLATE_PATH, dest)


def make_perfect(dest: Path) -> None:
    """Expectation: every one of 115 rows COMPLETE, workbook 100%."""
    wb, ws = _open_template()
    for row_num in range(FIRST_DATA_ROW, LAST_DATA_ROW + 1):
        _fill_row(ws, row_num, n=3)
    wb.save(dest)


def make_ragged(dest: Path) -> None:
    """H=4 agencies, K=3 names (slot 4 missing), L=2 phones (slots 3,4
    missing). Expectation: K and L PARTIAL at cell level with
    missing_slots=[4] / [3,4]; row REVIEW (slot_count_mismatch)."""
    wb, ws = _open_template()
    block = _valid_agency_block(ROW_SEHATGANJ, 4)
    k_lines = block["K"].split("\n")[:3]  # only 3 of 4 names
    l_lines = block["L"].split("\n")[:2]  # only 2 of 4 phones
    _fill_row(ws, ROW_SEHATGANJ, n=4, K="\n".join(k_lines), L="\n".join(l_lines))
    wb.save(dest)


def make_messy_format(dest: Path) -> None:
    """Same 2-agency data as a clean row, but H uses ')' markers and comma
    separation, L has extra spaces and an NBSP. Expectation: parses to the
    same N=2, same valid counts as an equivalently-filled clean row."""
    wb, ws = _open_template()
    _fill_row(
        ws, ROW_SEHATGANJ, n=2,
        H="1) Agency 1 Pvt Ltd,  2) Agency 2 Pvt Ltd",
        L=f"1.   {_phone(ROW_SEHATGANJ, 1)} \n2. {_phone(ROW_SEHATGANJ, 2)}",
    )
    wb.save(dest)


def make_unnumbered(dest: Path) -> None:
    """H has 2 agencies with no numbering at all. Expectation: positional
    fallback still finds 2 slots."""
    wb, ws = _open_template()
    _fill_row(ws, ROW_SEHATGANJ, n=2, H="Agency 1 Pvt Ltd\nAgency 2 Pvt Ltd")
    wb.save(dest)


def make_overflow(dest: Path) -> None:
    """8 agencies -- beyond the template's 6-slot scaffold. Expectation:
    N=8, nothing truncated."""
    wb, ws = _open_template()
    _fill_row(ws, ROW_SEHATGANJ, n=8)
    wb.save(dest)


def make_bad_dates(dest: Path) -> None:
    """J has a chain gap between slots and doesn't cover the window start.
    Expectation: date_chain_gap and date_window_coverage findings; row
    REVIEW even though every individual date is well-formed."""
    wb, ws = _open_template()
    j_override = (
        "1. 01/06/2021 - 10/11/2021\n"  # starts after window start -> coverage gap
        "2. 01/01/2022 - 14/01/2026"  # gap between slot 1 end and slot 2 start
    )
    _fill_row(ws, ROW_SEHATGANJ, n=2, J=j_override)
    wb.save(dest)


def make_bad_enums(dest: Path) -> None:
    """G is not a valid Plaza Type; I's values don't match EQ/Regular.
    Expectation: G and I both INVALID."""
    wb, ws = _open_template()
    _fill_row(ws, ROW_SEHATGANJ, n=2, G="Private", I="1. Yearly\n2. Yearly")
    wb.save(dest)


def make_bad_phones(dest: Path) -> None:
    """L has a 5-digit and an 11-digit number. Expectation: both slots
    INVALID with a shape-based reason."""
    wb, ws = _open_template()
    _fill_row(ws, ROW_SEHATGANJ, n=2, L="1. 98765\n2. 98765432109")
    wb.save(dest)


def make_identity_edited(dest: Path) -> None:
    """Plaza Name (C) changed for an otherwise-perfectly-filled row.
    Expectation: identity_mismatches non-empty, row REVIEW despite
    complete data."""
    wb, ws = _open_template()
    _fill_row(ws, ROW_SEHATGANJ, n=2)
    ws.cell(row=ROW_SEHATGANJ, column=COLUMNS["C"].index, value="SEHATGANJ EDITED")
    wb.save(dest)


def make_rows_inserted(dest: Path) -> None:
    """2 blank rows inserted above the data (after the header). Every
    plaza's physical row shifts down by 2. Expectation: still 115/115
    matched via S.No despite the shift."""
    wb, ws = _open_template()
    for row_num in range(FIRST_DATA_ROW, LAST_DATA_ROW + 1):
        _fill_row(ws, row_num, n=2)
    ws.insert_rows(FIRST_DATA_ROW, amount=2)
    wb.save(dest)


def make_na_marked(dest: Path) -> None:
    """L and S marked N/A on an otherwise-filled row. Expectation: both
    read NOT_APPLICABLE, not MISSING or INVALID."""
    wb, ws = _open_template()
    _fill_row(ws, ROW_SEHATGANJ, n=2, L="N/A", S="N/A")
    wb.save(dest)


VARIANTS = {
    "untouched.xlsx": make_untouched,
    "perfect.xlsx": make_perfect,
    "ragged.xlsx": make_ragged,
    "messy_format.xlsx": make_messy_format,
    "unnumbered.xlsx": make_unnumbered,
    "overflow.xlsx": make_overflow,
    "bad_dates.xlsx": make_bad_dates,
    "bad_enums.xlsx": make_bad_enums,
    "bad_phones.xlsx": make_bad_phones,
    "identity_edited.xlsx": make_identity_edited,
    "rows_inserted.xlsx": make_rows_inserted,
    "na_marked.xlsx": make_na_marked,
}


def generate_all(output_dir: Path = OUTPUT_DIR) -> dict[str, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}
    for filename, builder in VARIANTS.items():
        dest = output_dir / filename
        builder(dest)
        paths[filename] = dest
    return paths


if __name__ == "__main__":
    generated = generate_all()
    print(f"Generated {len(generated)} synthetic response workbooks in {OUTPUT_DIR}:")
    for name in generated:
        print(f"  {name}")
